from transformers import PreTrainedTokenizer, PreTrainedModel
import torch
try:
    from vllm.model_executor import set_random_seed as vllm_set_random_seed
    from vllm import LLM
    VLLM_AVAILABLE = True
except ImportError:
    VLLM_AVAILABLE = False
    vllm_set_random_seed = None
    LLM = None
from unittest.mock import patch

import os
import random
import numpy as np
from typing import Callable


def init_vllm(model_id: str, device: str, gpu_memory_utilization: float = 0.85):
    """ 
    Start the inference process, here we use vLLM to hold a model on a GPU separate from the policy.
    """

    # Monkeypatch from TRL:
    # https://github.com/huggingface/trl/blob/22759c820867c8659d00082ba8cf004e963873c1/trl/trainer/grpo_trainer.py 
    # Patch vLLM to make sure we can 
    # (1) place the vLLM model on the desired device (world_size_patch) and 
    # (2) avoid a test that is not designed for our setting (profiling_patch).

    world_size_patch = patch("torch.distributed.get_world_size", return_value=1)

    profiling_patch = patch( "vllm.worker.worker.Worker._assert_memory_footprint_increased_during_profiling", return_value=None)

    with world_size_patch, profiling_patch:
        return LLM(
            model=model_id, 
            device=device, 
            dtype=torch.bfloat16, 
            enable_prefix_caching=True, 
            gpu_memory_utilization=gpu_memory_utilization, 
        )

def load_policy_into_vllm_instance(policy: PreTrainedModel, llm):
    """ 
    Copied from https://github.com/huggingface/trl/blob/22759c820867c8659d00082ba8cf004e963873c1/trl/trainer/grpo_trainer.py#L670.
    """ 
    state_dict = policy.state_dict() 
    llm_model = llm.llm_engine.model_executor.driver_worker.model_runner.model 
    llm_model.load_weights(state_dict.items())

def set_seed(seed=42):
    """
    Sets the seed for reproducibility across python, numpy, and pytorch.
    """
    # 1. Base Python randomness
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    
    # 2. Numpy randomness
    np.random.seed(seed)
    
    # 3. PyTorch randomness
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)  # For multi-GPU setups
    
    # 4. CuDNN backend (Crucial for GPU reproducibility)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    if VLLM_AVAILABLE:
        vllm_set_random_seed(seed)

def log_generations(
    model: PreTrainedModel,
    tokenizer: PreTrainedTokenizer,
    input_prompt: list[str],
    ground_truth: list[str],
    reward_fn: Callable[[str, str], dict[str, float]], 
):
    """
    This function logs the following items
    1. The input prompt.
    2. The response generated by the SFT/RL model.
    3. The ground-truth answer.
    4. The reward information, including format, answer, and total reward.
    5. The average token entropy of the response.
    6. The average response length, average response length for correct responses, and average response length for incorrect responses.
    """

    # it's really hard to get the correct average entropy
    # the problem is that we use vllm for rollout, and vllm does not save raw logits
    # the only thing vllm provides is the top-k log probs
    # we are going to use this for entropy approximation
